### ISSUE TITLE
maya 2020 Error

### ISSUE THREAD

**Issue by Abdelrahimtd** [squarebit-studios/openrig#52]
Traceback (most recent call last):
  File "E:\nxt_maya\scripts\nxt_editor\connection_graphics_item.py", line 110, in paint
    painter.setRenderHints(False)
TypeError: 'PySide2.QtGui.QPainter.setRenderHints' called with wrong argument types:
  PySide2.QtGui.QPainter.setRenderHints(bool)
Supported signatures:
  PySide2.QtGui.QPainter.setRenderHints(PySide2.QtGui.QPainter.RenderHints, bool=True)

**Comment by matthew-schiller** [comment]
This looks NXT related. I would check there. https://github.com/nxt-dev/nxt_editor

**Comment by squarebit-studios** [comment]
Closed the issue due to this being an NXT error and is not related to the graph used in OpenRig.
